### ISSUE TITLE
Can I know the simulation settings?

### ISSUE THREAD

**Issue by Jianlan0816** [hhcho/densvis#11]
Hi, 

How did you generate the synthetic data? I only find a "trial.txt" file here but not the process of generating it. Could you let me know the process of it?

**Comment by anashwin** [comment]
Hi, 

Unfortunately I don't have saved the exact code that created the trial.txt file. 

However, the parameters of the data are: 
- 20 dimensions
- Six Gaussian point-clouds, with variance (isotropic) increasing geometrically for each point-cloud
- 500 points per point cloud
- Means chosen far away from each other (so there's no intersection between the point clouds)

Hopefully that helps!

**Comment by Jianlan0816** [comment]
Thanks so much.
