### ISSUE TITLE
Distribution as R package

### ISSUE THREAD

**Issue by alanocallaghan** [hhcho/densvis#4]
Would you have any objections if I package a (possibly slightly modified) version of this repository in an R package to submit to CRAN? Of course with appropriate credit and citation.

**Comment by anashwin** [comment]
Hi,

That would be wonderful! My R knowledge is extremely limited and if you had
any insight into the R issues people have brought up in the repo that would
also be much appreciated.

Ashwin

**Comment by alanocallaghan** [comment]
Great, thanks! I'll keep you posted. Since there's plans to integrate this into the python umap repo, per #2, I'll focus on densne, and later integrate densmap using [basilisk](https://bioconductor.org/packages/devel/bioc/html/basilisk.html)

**Comment by alanocallaghan** [comment]
I've got a working version as an R package so will either merge to the Rtsne repo or if they don't want it, a standalone, Quick question - is there a reason that some parameters are hardcoded (eg, here)? https://github.com/hhcho/densvis/blob/57c32692dbe5d0829c216f4179bbff140b5b04e4/densne/densne.cpp#L119-L120

**Comment by anashwin** [comment]
Hey,

Sorry for the late response. Great news about the working R package. Any
parameters that we hardcoded were also hardcoded in the original Barnes-Hut
t-SNE package (https://github.com/lvdmaaten/bhtsne). There is no ~real~
reason for them to be hardcoded!

Ashwin

**Comment by alanocallaghan** [comment]
No worries! Great thanks, I just wanted to be sure they weren't tuned for the density preservation.

**Comment by alanocallaghan** [comment]
https://bioconductor.org/packages/3.12/bioc/html/densvis.html :tada: 

(just realised you're not listed as author - I'll fix that soon)
